version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/testme
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
